# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3'
services:

  twitter-producer:
    container_name: twitter-ingest-container
    build:
      context: twitter-producer-svc
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - kafka
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: tail -F anything
    
  spark:
    container_name: spark-container
    build:
      context: spark-svc
      dockerfile: Dockerfile
    restart: unless-stopped
    entrypoint: python /app/app.py

  kafka:
    container_name: kafka-container
    # platform: linux/x86_64 # uncomment for m1 arm based macs
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  zookeeper:
    container_name: zookeeper-container
    # platform: linux/x86_64 # uncomment for m1 arm based macs
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  redis:
    container_name: redis-container
    image: "redis:alpine"
    restart: unless-stopped

  elasticsearch:
    container_name: elasticsearch-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - 9200:9200
    volumes:
      - data01:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana-container
    image: docker.elastic.co/kibana/kibana:7.11.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

volumes:
  data01:
    driver: local
