
# syntax=docker/dockerfile:1

FROM python:3.10-slim-buster

RUN apt-get update && apt-get -y install gcc telnet curl iputils-ping

WORKDIR /app

COPY requirements.txt requirements.txt
COPY requirements-test.txt requirements-test.txt

RUN \
    pip install --upgrade pip && \
    pip install -r requirements.txt -r requirements-test.txt


COPY . .

CMD [ "python3.10", "app.py"]


